name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: vandit-bera/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: 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
          USERNAME: vandit-bera
      - name: Commit & Push
        run: |
          git config vandit-bera github-actions
          git config vanditbera@gmail.com github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
